---
title: "Project #3: Escapades in Market Risk"
output: flexdashboard::flex_dashboard
---

```{r include=FALSE}
# ----------------------- Background section -------------------------
```

Background {data-orientation=columns}
=====================================  
    
Column {data-width=600}
-------------------------------------
    
### Problem

[Problem statement]

### Additional details

[project resources and info]

### Key business questions

[business questions]

Column {data-width=400}
-------------------------------------
   
### Getting a response: More detailed questions

[Detailed questions]

```{r include=FALSE}
# --------------------- Data Exploration section -----------------------
```

Data Exploration {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------

### Graphs

Metals Market Percent Changes
```{r}
# Add graphs
```
<br/><br/>

Metals Market Percent Changes - Size  
```{r}
# Add graph of size
```
   
### Data

Descriptive Statistics
```{r}
# Add min/1st qu/median/srd qu/max of nickel/copper/alum
```
<br/><br/>

Data Moments
```{r}
# Output the copper.size, alum.size, nickel.dir and copper.dir
# this should be mean, median, std_dev, IQR, skewness, kurtosis
```

Row {data-height=400}
-------------------------------------
    
### Data Insights

[Add data insights from graphs and data]
<br/><br/>

[Talk abut time frame, volatility, correlation, skewness andkurtosis]
